"""Add ImageSnapshot and UserImageAlert tables

Revision ID: a6863f7aec9a
Revises: b47e6acb1437
Create Date: 2026-03-29 15:46:29.627490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6863f7aec9a'
down_revision: Union[str, Sequence[str], None] = 'b47e6acb1437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_snapshots_captured_at'), 'image_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_image_snapshots_source'), 'image_snapshots', ['source'], unique=False)
    op.create_table('user_image_alerts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_time', sa.String(length=5), nullable=False),
    sa.Column('format_type', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_cubanomic_fetched_at', 'cubanomic_rates', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_history_snapshots_id'), 'history_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_snapshots_id'), table_name='history_snapshots')
    op.drop_index('ix_cubanomic_fetched_at', table_name='cubanomic_rates')
    op.drop_table('user_image_alerts')
    op.drop_index(op.f('ix_image_snapshots_source'), table_name='image_snapshots')
    op.drop_index(op.f('ix_image_snapshots_captured_at'), table_name='image_snapshots')
    op.drop_table('image_snapshots')
    # ### end Alembic commands ###
