"""Add CubanomicRate table

Revision ID: a77989368d5e
Revises: b123456789ab
Create Date: 2026-03-28 16:27:09.766771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77989368d5e'
down_revision: Union[str, Sequence[str], None] = 'b123456789ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubanomic_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usd_rate', sa.Float(), nullable=False),
    sa.Column('eur_rate', sa.Float(), nullable=False),
    sa.Column('mlc_rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cubanomic_rates_id'), 'cubanomic_rates', ['id'], unique=False)
    op.create_index(op.f('ix_cubanomic_rates_fetched_at'), 'cubanomic_rates', ['fetched_at'], unique=False)
    op.drop_index(op.f('ix_bot_command_stats_command'), table_name='bot_command_stats')
    op.drop_index(op.f('ix_bot_command_stats_created_at'), table_name='bot_command_stats')
    op.drop_index(op.f('ix_bot_command_stats_user_id'), table_name='bot_command_stats')
    op.drop_table('bot_command_stats')
    op.drop_table('bot_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('first_seen', sa.DATETIME(), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=False),
    sa.Column('total_commands', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bot_command_stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('command', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_command_stats_user_id'), 'bot_command_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_bot_command_stats_created_at'), 'bot_command_stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_command_stats_command'), 'bot_command_stats', ['command'], unique=False)
    op.drop_index(op.f('ix_cubanomic_rates_fetched_at'), table_name='cubanomic_rates')
    op.drop_index(op.f('ix_cubanomic_rates_id'), table_name='cubanomic_rates')
    op.drop_table('cubanomic_rates')
    # ### end Alembic commands ###
