"""Initial migration - create rate_snapshots and scheduler_status tables

Revision ID: a980a08ecd3a
Revises: 
Create Date: 2026-03-21 16:33:11.648321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a980a08ecd3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sell_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_snapshots_currency'), 'rate_snapshots', ['currency'], unique=False)
    op.create_index(op.f('ix_rate_snapshots_source'), 'rate_snapshots', ['source'], unique=False)
    op.create_table('scheduler_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_status')
    op.drop_index(op.f('ix_rate_snapshots_source'), table_name='rate_snapshots')
    op.drop_index(op.f('ix_rate_snapshots_currency'), table_name='rate_snapshots')
    op.drop_table('rate_snapshots')
    # ### end Alembic commands ###
