"""Add bot stats tables (bot_users, bot_command_stats)

Revision ID: c0f5e8a2b1d4
Revises: a6863f7aec9a
Create Date: 2026-05-06 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f5e8a2b1d4'
down_revision: Union[str, None] = 'a6863f7aec9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create bot_users table
    op.create_table(
        'bot_users',
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('first_name', sa.String(length=100), nullable=True),
        sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
        sa.Column('total_commands', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )

    # Create bot_command_stats table
    op.create_table(
        'bot_command_stats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('command', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['bot_users.user_id'], name='fk_bot_command_stats_user_id')
    )

    # Create indexes for performance
    op.create_index(op.f('ix_bot_command_stats_command'), 'bot_command_stats', ['command'], unique=False)
    op.create_index(op.f('ix_bot_command_stats_user_id'), 'bot_command_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_bot_command_stats_created_at'), 'bot_command_stats', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop foreign key
    op.drop_constraint('fk_bot_command_stats_user_id', 'bot_command_stats', type_='foreignkey')
    # Drop indexes
    op.drop_index(op.f('ix_bot_command_stats_created_at'), table_name='bot_command_stats')
    op.drop_index(op.f('ix_bot_command_stats_user_id'), table_name='bot_command_stats')
    op.drop_index(op.f('ix_bot_command_stats_command'), table_name='bot_command_stats')
    # Drop tables
    op.drop_table('bot_command_stats')
    op.drop_table('bot_users')

    # ### end Alembic commands ###
